### ISSUE TITLE
Add the feature of saving and loading the chat.

### ISSUE THREAD

**Issue by Reqience** [PygmalionAI/gradio-ui#13]
When you reboot, you have to start the chat every time anew.

**Comment by 0x000011b** [comment]
Yep, having to start the chat anew is very annoying. This is already a planned feature for the official UI, but while we're stuck with the prototype UI for now, @TearGosling @Reqience any of you willing to tackle this implementation?

**Comment by 0x000011b** [comment]
Implemented on #15.
