### ISSUE TITLE
Character Persona is broken.

### ISSUE THREAD

**Issue by ArkyMosuke** [PygmalionAI/gradio-ui#18]
Character persona box refuses to recognize even simple descriptors. Example included. 
![Screenshot_20230116_042112_Firefox](https://user-images.githubusercontent.com/122661567/212642552-f93a3863-a5bf-429b-89c4-176eabe1d331.png)
![Screenshot_20230116_042107_Firefox](https://user-images.githubusercontent.com/122661567/212642567-1ed0b89f-c5b2-4c1d-8ace-20580a86867f.png)

**Comment by 0x000011b** [comment]
Are these screenshots from the most recent model version? I can't seem to reproduce it there:
<img width="1013" alt="Screen Shot 2023-01-16 at 11 17 49" src="https://user-images.githubusercontent.com/121980126/212699430-0974292f-89fb-416d-8b3d-06eb352cb176.png">

The very first release _did_ have this problem though.

**Comment by ArkyMosuke** [comment]
It should be the lastest model, I did a fresh pull last night for everything, I could do another.

**Comment by ArkyMosuke** [comment]
Did another pull, both gradio and koboldAI are up to date.

**Comment by 0x000011b** [comment]
Ah, you're running Kobold on a local machine? If so, can you try forcing a re-download of the model somehow? Henk has confirmed to me that Kobold caches models locally and does not update them unless forced to, although I'm not sure what the process for doing that is.

**Comment by ArkyMosuke** [comment]
I see, well that's going to complicate things. Lemme get a friend in on this to help me figure that out real fast and I will get back to you.

**Comment by ArkyMosuke** [comment]
deleted KoboldAI-Client/models/PygmalionAI*
New model pull did it. Thank you! I have a script to delete them now and then just relaunch the services to pull it again.
