### ISSUE TITLE
Consider handling paragraphs/line breaks

### ISSUE THREAD

**Issue by 0x000011b** [PygmalionAI/gradio-ui#4]
Currently, Gradio's chatbot component eats up the newlines that the model generates. I _believe_ it can also receive and render HTML instead of raw text, so consider wrapping up each line in `<p>` tags and check if it improves readability.

**Comment by conanak99** [comment]
hi @0x000011b , linebreak for Gradio's chatbot can be simply added by replacing `\n` with `<br>`.

![image](https://user-images.githubusercontent.com/6670026/219938852-4897b4f8-5124-4074-a74d-1470c22631dc.png)

I can help make a PR for this, is that okay?

**Comment by 0x000011b** [comment]
Sure, that'd be super appreciated.

**Comment by conanak99** [comment]
> Sure, that'd be super appreciated.

I'm happy to help, made a pull request here https://github.com/PygmalionAI/gradio-ui/pull/34 :D
Tested the change by running new code in collab.
